-- MySQL Script generated by MySQL Workbench
-- 12/09/16 16:28:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stagex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stagex` ;

-- -----------------------------------------------------
-- Schema stagex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stagex` DEFAULT CHARACTER SET utf8 ;
USE `stagex` ;

-- -----------------------------------------------------
-- Table `stagex`.`webuser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`webuser` ;

CREATE TABLE IF NOT EXISTS `stagex`.`webuser` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`, `login`),
  UNIQUE INDEX `username_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`student` ;

CREATE TABLE IF NOT EXISTS `stagex`.`student` (
  `studentId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telphone` VARCHAR(45) NULL DEFAULT NULL,
  `garde` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `motivation` VARCHAR(45) NULL DEFAULT NULL,
  `cv` VARCHAR(45) NULL DEFAULT NULL,
  `picture` VARCHAR(45) NULL DEFAULT NULL,
  `socialSecruityNum` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`studentId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `Student_FK_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `stagex`.`webuser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`apply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`apply` ;

CREATE TABLE IF NOT EXISTS `stagex`.`apply` (
  `applyId` INT(11) NOT NULL,
  `studentId` INT(11) NULL DEFAULT NULL,
  `applyAddress` VARCHAR(45) NULL DEFAULT NULL,
  `applyTelphone` VARCHAR(45) NULL DEFAULT NULL,
  `chargePersonContact` VARCHAR(45) NULL DEFAULT NULL,
  `decription` VARCHAR(45) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `benefit` INT(11) NULL DEFAULT NULL,
  `healthInsurance` TINYINT(1) NULL DEFAULT NULL,
  `workTrip` TINYINT(1) NULL DEFAULT NULL,
  `bossFirstName` VARCHAR(45) NULL DEFAULT NULL,
  `bossLastName` VARCHAR(45) NULL DEFAULT NULL,
  `bossJob` VARCHAR(45) NULL DEFAULT NULL,
  `bossEmail` VARCHAR(45) NULL DEFAULT NULL,
  `bossTelphone` VARCHAR(45) NULL DEFAULT NULL,
  `bossFax` VARCHAR(45) NULL DEFAULT NULL,
  `wayFindApply` VARCHAR(45) NULL DEFAULT NULL,
  `companyPrestation` VARCHAR(45) NULL DEFAULT NULL,
  `companyContast` VARCHAR(45) NULL DEFAULT NULL,
  `applyGoal` VARCHAR(45) NULL DEFAULT NULL,
  `pricipleSteps` VARCHAR(45) NULL DEFAULT NULL,
  `applyRequirement` VARCHAR(45) NULL DEFAULT NULL,
  `validate` TINYINT(1) NULL DEFAULT NULL,
  `companyId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`applyId`),
  INDEX `studentId_idx` (`studentId` ASC),
  CONSTRAINT `Apply_FK_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `stagex`.`student` (`studentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`company` ;

CREATE TABLE IF NOT EXISTS `stagex`.`company` (
  `companyId` INT(11) NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NULL DEFAULT NULL,
  `siretNumber` INT(11) NULL DEFAULT NULL,
  `codeApe` VARCHAR(45) NULL DEFAULT NULL,
  `companyAddress` VARCHAR(45) NULL DEFAULT NULL,
  `receptionName` VARCHAR(45) NULL DEFAULT NULL,
  `telphone` VARCHAR(45) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`companyId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`experience` ;

CREATE TABLE IF NOT EXISTS `stagex`.`experience` (
  `experienceId` INT(11) NOT NULL AUTO_INCREMENT,
  `jobType` VARCHAR(45) NULL DEFAULT NULL,
  `jobName` VARCHAR(45) NULL DEFAULT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `companyName` VARCHAR(45) NULL DEFAULT NULL,
  `loction` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`experienceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`offer` ;

CREATE TABLE IF NOT EXISTS `stagex`.`offer` (
  `offerId` INT(11) NOT NULL AUTO_INCREMENT,
  `companyId` INT(11) NULL DEFAULT NULL,
  `contactFirstName` VARCHAR(45) NULL DEFAULT NULL,
  `contactLastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `job` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `profileRequirement` VARCHAR(45) NULL DEFAULT NULL,
  `abilityRequirement` VARCHAR(45) NULL DEFAULT NULL,
  `loction` VARCHAR(45) NULL DEFAULT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  `validate` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`offerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`studentexperience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`studentexperience` ;

CREATE TABLE IF NOT EXISTS `stagex`.`studentexperience` (
  `studentId` INT(11) NOT NULL,
  `experienceId` INT(11) NOT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `StudentExperiencecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`studentId`, `experienceId`),
  INDEX `experienceId_idx` (`experienceId` ASC),
  CONSTRAINT `SE_FK_experienceId`
    FOREIGN KEY (`experienceId`)
    REFERENCES `stagex`.`experience` (`experienceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SE_FK_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `stagex`.`student` (`studentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stagex`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagex`.`teacher` ;

CREATE TABLE IF NOT EXISTS `stagex`.`teacher` (
  `teacherId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `subject` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telphone` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`teacherId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `Teacher_FK_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `stagex`.`webuser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
