-- MySQL Script generated by MySQL Workbench
-- 12/03/16 10:50:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stageX
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stageX` ;

-- -----------------------------------------------------
-- Schema stageX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stageX` DEFAULT CHARACTER SET utf8 ;
USE `stageX` ;

-- -----------------------------------------------------
-- Table `stageX`.`WebUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`WebUser` ;

CREATE TABLE IF NOT EXISTS `stageX`.`WebUser` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Student` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Student` (
  `studentId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `garde` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `motivation` VARCHAR(45) NULL,
  `cv` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `socialSecruityNum` VARCHAR(45) NULL,
  PRIMARY KEY (`studentId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `Student_FK_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `stageX`.`WebUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Teacher` (
  `teacherId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`teacherId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `Teacher_FK_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `stageX`.`WebUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Experience` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Experience` (
  `experienceId` INT NOT NULL AUTO_INCREMENT,
  `jobType` VARCHAR(45) NULL,
  `jobName` VARCHAR(45) NULL,
  `salary` INT NULL,
  `companyName` VARCHAR(45) NULL,
  `loction` VARCHAR(45) NULL,
  PRIMARY KEY (`experienceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`StudentExperience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`StudentExperience` ;

CREATE TABLE IF NOT EXISTS `stageX`.`StudentExperience` (
  `studentId` INT NOT NULL,
  `experienceId` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `description` VARCHAR(45) NULL,
  `StudentExperiencecol` VARCHAR(45) NULL,
  PRIMARY KEY (`studentId`, `experienceId`),
  INDEX `experienceId_idx` (`experienceId` ASC),
  CONSTRAINT `SE_FK_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `stageX`.`Student` (`studentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SE_FK_experienceId`
    FOREIGN KEY (`experienceId`)
    REFERENCES `stageX`.`Experience` (`experienceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Company` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Company` (
  `companyId` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NULL,
  `siretNumber` INT NULL,
  `codeApe` VARCHAR(45) NULL,
  `companyAddress` VARCHAR(45) NULL,
  `receptionName` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`companyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Offer` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Offer` (
  `offerId` INT NOT NULL AUTO_INCREMENT,
  `companyId` INT NULL,
  `contactFirstName` VARCHAR(45) NULL,
  `contactLastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `job` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `profileRequirement` VARCHAR(45) NULL,
  `abilityRequirement` VARCHAR(45) NULL,
  `loction` VARCHAR(45) NULL,
  `salary` INT NULL,
  `duration` VARCHAR(45) NULL,
  PRIMARY KEY (`offerId`),
  INDEX `companyId_idx` (`companyId` ASC),
  CONSTRAINT `Offer_FK_companyId`
    FOREIGN KEY (`companyId`)
    REFERENCES `stageX`.`Company` (`companyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stageX`.`Apply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stageX`.`Apply` ;

CREATE TABLE IF NOT EXISTS `stageX`.`Apply` (
  `applyId` INT NOT NULL,
  `studentId` INT NULL,
  `applyAddress` VARCHAR(45) NULL,
  `applyTelphone` VARCHAR(45) NULL,
  `chargePersonContact` VARCHAR(45) NULL,
  `decription` VARCHAR(45) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `salary` INT NULL,
  `benefit` INT NULL,
  `healthInsurance` TINYINT(1) NULL,
  `workTrip` TINYINT(1) NULL,
  `bossFirstName` VARCHAR(45) NULL,
  `bossLastName` VARCHAR(45) NULL,
  `bossJob` VARCHAR(45) NULL,
  `bossEmail` VARCHAR(45) NULL,
  `bossTelphone` VARCHAR(45) NULL,
  `bossFax` VARCHAR(45) NULL,
  `wayFindApply` VARCHAR(45) NULL,
  `companyPrestation` VARCHAR(45) NULL,
  `companyContast` VARCHAR(45) NULL,
  `applyGoal` VARCHAR(45) NULL,
  `pricipleSteps` VARCHAR(45) NULL,
  `applyRequirement` VARCHAR(45) NULL,
  PRIMARY KEY (`applyId`),
  INDEX `studentId_idx` (`studentId` ASC),
  CONSTRAINT `Apply_FK_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `stageX`.`Student` (`studentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE `stagex`.`webuser` 
ADD COLUMN `userName` VARCHAR(45) NOT NULL AFTER `password`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`userId`, `userName`),
ADD UNIQUE INDEX `username_UNIQUE` (`userName` ASC);

